name: camelmovies
description: caMel, your favourite app to discover millions of movies.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  retry: ^3.1.0
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/apikey.txt

  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
