name: camelmovies
description: caMel, your favourite app to discover millions of movies.

publish_to: 'none'

version: 1.1.0+6

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  path: ^1.8.0
  postor: ^0.0.3+0
  retry: ^3.1.0
  rxdart: ^0.27.1
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/apikey.txt

  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
