name: camelapp
description: caMel, your favourite app to discover millions of movies & tv shows.

publish_to: 'none'

version: 1.3.2

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.1.0
  config:
    path: config
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_cache_manager: ^3.1.2
  get_it: ^7.2.0
  intl: ^0.17.0
  path: ^1.8.0
  postor: ^0.0.4+1
  rxdart: ^0.27.1
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:

  uses-material-design: true

  assets:
    - assets/apikey.txt

  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
